PROJECT:
  name: 'DenseFuse_Image_Fusion'
  save_path: './work_dirs/'

TRAIN_DATASET:
  root_dir: './datasets/TNO/'
  sensors: [ 'Vis', 'Inf' ]
  channels: 1
  input_size: 256
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TRAIN:
  batch_size: 8
  gpu_id: 1
  max_epoch: 2000
  lr: 0.01
  gamma: 0.01
  milestones: [ 1000, 1500, 1750 ]
  opt: Adam
  loss_func: ['Dist_Loss', 'SSIM_Loss']
  val_interval: 1
  debug_interval: 100
  resume: None
  loss_weights: [ 1, 1000 ]

TEST_DATASET:
  root_dir: './datasets/TNO/'
  sensors: [ 'Vis', 'Inf' ]
  channels: 1
  input_size: 256
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TEST:
  batch_size: 2
  weight_path: './work_dirs/DenseFuse_Image_Fusion/model_2000.pth'
  save_path: './test/'

MODEL:
  model_name: 'DenseFuse'
  input_channels: 1
  out_channels: 16
  input_sensors: [ 'Vis', 'Inf' ]
  coder_layers: 4
  decoder_layers: 4
