PROJECT:
  name: 'VIF_Net_Image_Fusion'
  save_path: './work_dirs/'

TRAIN_DATASET:
  root_dir: './datasets/TNO/'
  sensors: [ 'Vis', 'Inf' ]
  channels: 1
  input_size: 256
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TRAIN:
  batch_size: 8
  max_epoch: 200
  lr: 0.01
  gamma: 0.01
  milestones: [ 100, 150, 175 ]
  opt: Adam
  loss_func: ['VIF_SSIM_Loss', 'TV_Loss']
  val_interval: 1
  debug_interval: 100
  resume: None
  loss_weights: [ 1000, 1 ]

TEST_DATASET:
  root_dir: './datasets/TNO/'
  sensors: [ 'Vis', 'Inf' ]
  channels: 1
  input_size: 256
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TEST:
  batch_size: 2
  weight_path: './work_dirs/VIF_Net_Image_Fusion/model_100.pth'
  save_path: './test/'

MODEL:
  model_name: 'VIF_Net'
  input_channels: 1
  out_channels: 16
  input_sensors: [ 'Vis', 'Inf' ]
  coder_layers: 4
  decoder_layers: 4
